### ISSUE TITLE
Missing import "NSManagedObject+MagicalRecord.h" in ATCalendar.m

### ISSUE THREAD

**Issue by Narayane** [adriantofan/ATCalendar#2]
Hi,

I have another problem with MR_\* directives.

![at_missing](https://cloud.githubusercontent.com/assets/4921308/13356255/a0b9cec8-dca4-11e5-8778-713d747e6a49.png)

it misses #import "NSManagedObject+MagicalRecord.h" in ATCalendar.m in this case but when I add it, same error appears in others files. Can you add this import in your .pch file please ?

Thanks

**Comment by adriantofan** [comment]
the MR_ stuff is now inside <MagicalRecord/MagicalRecord.h>  and as you can see I've updated the project to use it. Maybe we are not using the same version of Magical Record ?
Anyway, if you wish to use another version of MagicalRecord you can fork the project, the fix for your last issue is easy to find in my last commit

**Comment by Narayane** [comment]
I use 'MagicalRecord', '2.2'

**Comment by adriantofan** [comment]
in the project you have the Podfile.lock file and you can compare versions with yours. maybe is a cocoapods incompatibility. I've switched to 0.39.0.  For me it compiles just fine.

**Comment by Narayane** [comment]
Hi,

what I understand of my problem is you use MagicalRecord Shorthands mechanism by calling MR_methods.

But, when I use your pod, all MR_methods of your pod code are unrecognized because of #import < MagicalRecord/MagicalRecord.h > use instead of #import "CoreData+MagicalRecord.h". (https://github.com/magicalpanda/MagicalRecord/issues/403)

I can solve this problem by replacing the first import by the second by unlocking your pod code but it is not a good solution from my point of view.

Would it be possible that you define MR_SHORTHAND before #import "CoreData+MagicalRecord.h" in your pch file and remove any # import < MagicalRecord/MagicalRecord.h > occurrences in your ATClasses ?

Thanks.

**Comment by adriantofan** [comment]
I remind you that if you download the test project everything works fine, so the problem must be in your setup. As I've explained you previously either your pods(your libraries) are different or cocoapods is different.  Don't look for another fix.

If you don't want or can't change your setup, fork the project and apply my last fix (one line of code) to your fork, than use your fork.

**Comment by adriantofan** [comment]
this is the one line fix that I was telling you about

<img width="1214" alt="minimal_fixes_sot_that_it_builds_with_version_7_2_1_ _adriantofan_atcalendar_3ac400e" src="https://cloud.githubusercontent.com/assets/750147/13433930/53263f42-dfd4-11e5-93a2-1bf25329ce66.png">

inside of Classes/Models/ATEvent+LocalNotifications.m

**Comment by legars** [comment]
Hi,

We have a problem with the latest version. 
Now when I change the selectedDisplayStyle with the segCtrl we have bug.
My application freeze. I search for a workaround but without success.
It seems that the problem is with MagicalRecord and performBlockAndWait function.

The problem is not present on iOS 7 but only on iOS 8 and more.

Thanks for your answer

Regards

**Comment by adriantofan** [comment]
I am sorry, but I am not supporting this project anymore.
